site_name: Mahiru Documentation
site_url: https://docs.mahiru.one
site_description: Meet Mahiru, cutest Telegram bot! With versatile features, Mahiru can brighten up your day and assist in daily tasks.
theme:
  name: material
  favicon: assets/logo.png
  logo: assets/logo.png
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: fontawesome/solid/moon
        name: Switch to dark mode
      primary: custom
      accent: custom
    - scheme: slate 
      toggle:
        icon: fontawesome/solid/sun
        name: Switch to light mode    
      primary: custom
      accent: custom
  icon:
    tag:
      sections: octicons/rows-24
      секции: octicons/rows-24
      dashboard: octicons/browser-24
      панель: octicons/browser-24
      настройки: octicons/gear-24
      settings: octicons/gear-24
      image: octicons/file-media-24
      изображение: octicons/file-media-24
      genshin: material/gamepad-variant-outline
      геншин: material/gamepad-variant-outline
      nsfw: octicons/circle-slash-24
      version_1_0_0: octicons/tag-24
      версия_1_0_0: octicons/tag-24
      command: octicons/code-24
      команда: octicons/code-24
      inline: octicons/paperclip-24
      встроенная: octicons/paperclip-24

extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/MahiruShiinaBot
    - icon: fontawesome/brands/github 
      link: https://github.com/MahiruBot/mahirubot.github.io
  tags:
    Секции: секции
    Sections: sections
    Настройки: настройки
    Settings: settings
    Панель управления: панель
    Dashboard: dashboard
    Image: image
    Изображение: изображение
    NSFW: nsfw
    Геншин: геншин
    Genshin: genshin
    Version 1.0.0: version_1_0_0
    Версия 1.0.0: версия_1_0_0
    Command: command
    Команда: команда
    Inline command: inline
    Встроенная команда: встроенная
  generator: false

extra_css:
  - stylesheets/custom.css

plugins:
  - tags
  - search:
      lang: 
        - en
        - ru
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          site_name: Mahiru Documentation
          site_description: Meet Mahiru, cutest Telegram bot! With versatile features, Mahiru can brighten up your day and assist in daily tasks.
          build: true
          default: true
          theme:
            palette:
              - scheme: default
                toggle:
                  name: Switch to dark mode
              - scheme: slate 
                toggle:
                  name: Switch to light mode
          nav_translations:
            Home: Home
            Pages: Pages
            Profile: Profile
            Genshin: Genshin
            Language: Language
            Sections: Sections
            Settings: Settings
            Commands: Commands
            Dashboard: Dashboard
            Anime lists: Anime Lists
            Manga lists: Manga Lists
            NSFW content: NSFW Content
            Commands list: Commands list
            For developers: For Developers
            Common commands: Common Commands
            Genshin commands: Genshin Commands
            Game integrations: Game Integrations
            Genshin Integration: Genshin Integration 
        - locale: ru 
          name: Русский
          site_name: Документация Махиру
          site_description: Знакомьтесь, Махиру, самый милый Телеграм-бот! Благодаря универсальным функциям Махиру может скрасить ваш день и помочь в повседневных задачах.
          build: true
          theme:
            palette:
              - scheme: default
                toggle:
                  name: Включить тёмную тему
              - scheme: slate 
                toggle:
                  name: Включить светлую тему
          nav_translations:
            Home: Главная
            Pages: Страницы
            Profile: Профиль
            Genshin: Геншин
            Language: Язык  
            Sections: Секции
            Settings: Настройки
            Commands: Команды
            Dashboard: Панель управления
            Anime Lists: Списки аниме
            Manga Lists: Списки манги
            NSFW Content: Откровенный контент
            Commands list: Список команд
            For Developers: Для разработчиков
            Common commands: Обычные команды
            Genshin commands: Геншин команды
            Game Integrations: Игровые интеграции
            Genshin Integration: Интеграция Геншина
  - git-revision-date-localized:
      enable_creation_date: true
  - social:
      cards_layout_options:
        background_color: "#e6bba7"

markdown_extensions:
  - meta
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - index.md
  - Commands:
    - commands/default-commands.md
    - commands/inline-commands.md
    - Commands list:
      - Common commands:
        - /anime: commands/commands-list/common/anime.md
        - /animelist: commands/commands-list/common/animelist.md
        - /end: commands/commands-list/common/end.md
        - /game: commands/commands-list/common/game.md
        - /gif: commands/commands-list/common/gif.md
        - /gpt: commands/commands-list/common/gpt.md
        - /help: commands/commands-list/common/help.md
        - /imgtotext: commands/commands-list/common/imgtotext.md
        - /manga: commands/commands-list/common/manga.md
        - /mangalist: commands/commands-list/common/mangalist.md
        - /nsfw: commands/commands-list/common/nsfw.md
        - /song: commands/commands-list/common/song.md
        - /video: commands/commands-list/common/video.md
        - /waifu: commands/commands-list/common/waifu.md
        - /waifunsfw: commands/commands-list/common/waifunsfw.md
      - Genshin commands:
        - /genshin_abyss: commands/commands-list/genshin/abyss.md
        - /genshin_check: commands/commands-list/genshin/check.md
        - /genshin_exploration: commands/commands-list/genshin/exploration.md
        - /genshin_characters: commands/commands-list/genshin/characters.md
        - /genshin_notes: commands/commands-list/genshin/notes.md
        - /genshin_profile: commands/commands-list/genshin/profile.md
        - /genshin_redeem: commands/commands-list/genshin/redeem.md
        - /genshin_tcg: commands/commands-list/genshin/tcg.md
        - /genshin_teapot: commands/commands-list/genshin/teapot.md
  - Dashboard:
    - dashboard/introduction.md
    - Pages:
      - Sections:
        - Profile: dashboard/pages/sections/profile.md
        - Anime Lists: dashboard/pages/sections/anime-lists.md
        - Manga Lists: dashboard/pages/sections/manga-lists.md
      - Game Integrations:
        - Genshin Integration: dashboard/pages/game-integrations/genshin.md
      - Settings:
        - Commands:
          - GPT: dashboard/pages/settings/commands/gpt.md
        - Language: dashboard/pages/settings/language.md
        - NSFW Content: dashboard/pages/settings/nsfw-content.md
        - For Developers: dashboard/pages/settings/for-developers.md
  - API:
    - api/genshin-images.md

copyright: |
  &copy; 2023 <a href="https://github.com/jokelbaf"  target="_blank" rel="noopener">JokelBaf</a>